name: Executar testes

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Configurar o ambiente
        run: |
          # Projeto Node.js
          npm install
      - name: Executar testes
        run: |
          # Projeto Node.js com Jest
          npm test
