name: Continiuous Integration;
on: pull_request;
# JOBS => PASSO A PASSO 
jobs: 
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v3
        - name: Using Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '14'
            - name: run Install, Build and Test
              run: |
                npm install
                npm run build
                npm test
